apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zkrl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zkrl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zkrl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zkrl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zkrl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pptf-tenant/rhtap-demo-app/hacbs-test-project-zkrl@sha256:3d636714061361bf07500182b3df67a4d8eedbc79a3a8896ca75a410876287cf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
